id: AzureCompute-Test
version: -1
name: AzureCompute-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1c88c7a0-a4e6-4ce7-89f2-d6b5a8f4e7e5
    type: start
    task:
      id: 1c88c7a0-a4e6-4ce7-89f2-d6b5a8f4e7e5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 22b9c613-06c4-4c98-88b0-e8b81a12f8a0
    type: regular
    task:
      id: 22b9c613-06c4-4c98-88b0-e8b81a12f8a0
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 11fe238e-9d5f-4f37-8730-c9bbf6991ee8
    type: regular
    task:
      id: 11fe238e-9d5f-4f37-8730-c9bbf6991ee8
      version: -1
      name: azure-vm-create-instance
      description: Create a virtual machine instance with the specified OS image
      script: Azure Compute|||azure-vm-create-instance
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      admin_password: {}
      admin_username: {}
      image:
        simple: Ubuntu Server 16.04 LTS
      location:
        simple: westeurope
      nic_id:
        simple: compute-integration-nic
      offer: {}
      publisher: {}
      resource_group:
        simple: compute-integration
      sku: {}
      version: {}
      virtual_machine_name:
        simple: NightlyTest
      vm_size:
        simple: Standard_D1_v2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 7fc946b9-13ae-42d4-8743-035379421fc0
    type: condition
    task:
      id: 7fc946b9-13ae-42d4-8743-035379421fc0
      version: -1
      name: Verify Create Instance
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "20"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Azure.Compute.ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 7de811cd-8e56-41c6-8ae3-d661f0055c13
    type: regular
    task:
      id: 7de811cd-8e56-41c6-8ae3-d661f0055c13
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: c47746c9-651b-4bac-813a-fb4f6490e14e
    type: regular
    task:
      id: c47746c9-651b-4bac-813a-fb4f6490e14e
      version: -1
      name: azure-list-resource-groups
      description: List all Resource Groups belonging to your Azure subscription
      script: Azure Compute|||azure-list-resource-groups
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: ac5693e4-7268-4c6b-89ad-6153ed30ce23
    type: regular
    task:
      id: ac5693e4-7268-4c6b-89ad-6153ed30ce23
      version: -1
      name: azure-vm-start-instance
      description: Power-on a specified Virtual Machine
      script: Azure Compute|||azure-vm-start-instance
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      resource_group:
        simple: compute-integration
      virtual_machine_name:
        simple: NightlyTest
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: 1cb83d49-85f0-4193-8f7b-ff2e26ff6913
    type: regular
    task:
      id: 1cb83d49-85f0-4193-8f7b-ff2e26ff6913
      version: -1
      name: azure-vm-poweroff-instance
      description: Power-off a specified Virtual Machine
      script: Azure Compute|||azure-vm-poweroff-instance
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      resource_group:
        simple: compute-integration
      virtual_machine_name:
        simple: NightlyTest
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: 44112793-137b-465d-8084-158a4c8287eb
    type: regular
    task:
      id: 44112793-137b-465d-8084-158a4c8287eb
      version: -1
      name: azure-vm-get-instance-details
      description: Get the properties of a specified Virtual Machine
      script: Azure Compute|||azure-vm-get-instance-details
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      resource_group:
        simple: compute-integration
      virtual_machine_name:
        simple: NightlyTest
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: d92b5a51-01e0-49e5-892a-604c9f0ee18c
    type: regular
    task:
      id: d92b5a51-01e0-49e5-892a-604c9f0ee18c
      version: -1
      name: azure-vm-list-instances
      description: List the VM instances in the specified Resource Group
      script: Azure Compute|||azure-vm-list-instances
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      resource_group:
        simple: compute-integration
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: c4abad9c-7fb3-4ded-81ad-f9a160497c4a
    type: regular
    task:
      id: c4abad9c-7fb3-4ded-81ad-f9a160497c4a
      version: -1
      name: azure-vm-delete-instance
      description: Delete a specified Virtual Machine
      script: Azure Compute|||azure-vm-delete-instance
      type: regular
      iscommand: true
      brand: Azure Compute
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      resource_group:
        simple: compute-integration
      virtual_machine_name:
        simple: NightlyTest
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3520
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: eaf0041f-0bb9-47b9-8973-1cd6fc5a4162
    type: condition
    task:
      id: eaf0041f-0bb9-47b9-8973-1cd6fc5a4162
      version: -1
      name: Verify List Resource Groups
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: in
          left:
            value:
              simple: compute-integration
          right:
            value:
              simple: Azure.ResourceGroup.Name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "12":
    id: "12"
    taskid: 5cdcf608-a1c7-48cd-8403-c2c4c84632a3
    type: regular
    task:
      id: 5cdcf608-a1c7-48cd-8403-c2c4c84632a3
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: 7af14dab-c396-4274-8f1b-6fdf47eb5fb7
    type: condition
    task:
      id: 7af14dab-c396-4274-8f1b-6fdf47eb5fb7
      version: -1
      name: Verify List Instances
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Azure.Compute.OS
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: 32219ca9-3e47-43a8-80a8-d5946d3fde8d
    type: condition
    task:
      id: 32219ca9-3e47-43a8-80a8-d5946d3fde8d
      version: -1
      name: Verify Start Instance
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Azure.Compute.PowerState
            iscontext: true
          right:
            value:
              simple: VM running
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: 5b76e3b3-694d-45e7-8e1f-e4cfd720c9b6
    type: regular
    task:
      id: 5b76e3b3-694d-45e7-8e1f-e4cfd720c9b6
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep:
        simple: InstanceID
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: b7689a83-b71a-4810-804b-2f7db1f53dfe
    type: regular
    task:
      id: b7689a83-b71a-4810-804b-2f7db1f53dfe
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
  "17":
    id: "17"
    taskid: badacfc0-a1f3-4834-8904-0a3844ab70fb
    type: condition
    task:
      id: badacfc0-a1f3-4834-8904-0a3844ab70fb
      version: -1
      name: Verify Get Instance & Poweroff Instance
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Azure.Compute.PowerState
            iscontext: true
          right:
            value:
              simple: VM stopped
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3345
        }
      }
    note: false
    timertriggers: []
  "18":
    id: "18"
    taskid: 6eef9ceb-59c4-4e7f-80c9-bcf2dbf82d04
    type: title
    task:
      id: 6eef9ceb-59c4-4e7f-80c9-bcf2dbf82d04
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3695
        }
      }
    note: false
    timertriggers: []
  "19":
    id: "19"
    taskid: d2bc769c-925b-4d76-8252-afb27a74b5f9
    type: regular
    task:
      id: d2bc769c-925b-4d76-8252-afb27a74b5f9
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
  "20":
    id: "20"
    taskid: 8454ce50-b44f-40f3-8d69-a6ac3ba3cd3f
    type: regular
    task:
      id: 8454ce50-b44f-40f3-8d69-a6ac3ba3cd3f
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      seconds:
        simple: "300"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "21":
    id: "21"
    taskid: 4e4b86ca-2dc3-42a8-8be3-1c8c1097e896
    type: regular
    task:
      id: 4e4b86ca-2dc3-42a8-8be3-1c8c1097e896
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3710,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
